### ISSUE TITLE
Fatal error during start

### ISSUE THREAD

**Issue by petikeje** [timonier/extract-xiso#2]
Hi,
I have installed extract-xiso based on hub.docker.com on my raspberry pi
After the command extract-xiso -h I get the following error:
FATAL tini (7)] exec dumb-entrypoint failed: Exec format error
Could you please help me what's wrong?
THX:
 P!

**Comment by mauchede** [comment]
Hello @petikeje,

Sorry for the late response. I fixed `timonier/dumb-entrypoint` some weeks ago. I just test on my computer and It works. Could you retry and tell me if it works for you too?

**Comment by petikeje** [comment]
Hi,
I have tested, but I get the same error. Maybe I do something wrong:
I installed Docker: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
I installed dumb-init dumb-entrypoint gosu s6-overlay version-listener and extract-xiso in a remote installation way but I still get the error [FATAL tini (8)] exec dumb-entrypoint failed: Exec format error.
Best regards:
 P!

**Comment by mauchede** [comment]
[dumb-entrypoint](https://github.com/timonier/dumb-entrypoint) does not have to be installed on your computer: it is installed in the Docker image.

Did you retrieve the latest image and install the latest command before trying? If no, could you run the following command and try again:

```sh
# Retrieve latest image
docker pull timonier/extract-xiso

# Update "extract-xiso" command
curl --location "https://github.com/timonier/extract-xiso/raw/master/bin/installer" | sudo sh -s -- install
```
